Repository OZ11-OneTurnOneKill/front-end, pull requests merged in 2025-08, with the labels that each got.

#3 Git 컨벤션 템플릿 & Tailwind CSS v4.1 세팅
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  index.html
  package-lock.json
  package.json
  src/App.css
  vite.config.ts
Labels: init

#24 hotfix: rollup 에러 수정
  package-lock.json
  package.json
Labels: bug

#26 hotfix: react-calendar 라이브러리 package-lock 수정
  package-lock.json
Labels: bug

#27 hotfix: mac 개발자를 위한 "@rollup/rollup-win32-x64-msvc": "^4.46.2" 삭제
  package-lock.json
  package.json
Labels: bug

#29 Feat/15 footer component
  src/App.tsx
  src/footer/Footer.tsx
  src/header/Header.tsx
Labels: enhancement

#33 Bug/32 npm build error
  .eslintrc.cjs
  eslint.config.js
  package-lock.json
  package.json
  src/App.tsx
  src/landing/LandingPage.tsx
  src/main.tsx
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
Labels: bug

#35 rename: 폴더명 소문자로 수정
  src/App.tsx
  src/community/CommunityLayout.tsx
Labels: chore

#37 rename: Category 폴더명에서 category로 바뀌도록 시스템에서 변경
  src/community/category/CommunityAll.tsx
  src/community/category/CommunityFree.tsx
  src/community/category/CommunityShare.tsx
  src/community/category/CommunityStudy.tsx
Labels: bug

#38 [CHORE] 배포를 위한 병합 작업
  src/community/category/CommunityAll.tsx
  src/community/category/CommunityFree.tsx
  src/community/category/CommunityShare.tsx
  src/community/category/CommunityStudy.tsx
Labels: chore

#41 [FEAT] 게시글 공통 수기 검증 폼 구현 및 api type 및 함수 구현
  package-lock.json
  package.json
  src/community/api/community.ts
  src/community/api/http.ts
  src/community/api/types.ts
  src/community/form/CreatePost.tsx
  src/community/form/EditPost.tsx
  src/community/form/PostForm.tsx
Labels: enhancement

#48 [FEAT] mypage의 component (posts & content) 기능 구현
  src/header/Header.tsx
  src/mypage/Mypage.tsx
  src/mypage/components/MypageContent.tsx
Labels: enhancement

#52 [FEAT] 마이페이지 challenge 기능 임시 구현
  src/mypage/components/Challenge.tsx
  src/mypage/components/MypageContent.tsx
Labels: enhancement

#62 [FIX] 대댓글 중첩현상 발생
  src/community/__mock__/dummyPost.ts
  src/community/hook/useComments.ts
  src/community/post/PostDetail.tsx
  src/community/post/components/CommentForm.tsx
  src/community/post/components/CommentItem.tsx
  src/community/post/components/CommentList.tsx
  src/community/utils/commentTree.ts
Labels: bug

#74 [FEAT] AI 기능 API 연결
  .gitignore
  src/App.tsx
  src/ai/AiPage.tsx
  src/ai/api/http.ts
  src/ai/api/sidebarTitle.ts
  src/ai/api/studyPlan.ts
  src/ai/api/summary.ts
  src/ai/components/AISideItem.tsx
  src/ai/components/AiMain.tsx
  src/ai/components/AiSideBar.tsx
  src/ai/components/ChatList.tsx
  src/ai/hook/useStudyPlanInfiniteList.ts
  src/ai/hook/useUnifiedAiFeed.ts
  src/ai/types/types.ts
  src/landing/LandingPage.tsx
  src/landing/components/BenefitLanding.tsx
  vite.config.ts
Labels: enhancement

#76 [FEAT] nickname update
  src/mypage/components/MypageContent.tsx
Labels: enhancement

#80 [FEAT] 로그인 전 api호출로인한 401에러
  src/App.tsx
  src/store/authStore.ts
Labels: enhancement

#83 [BUG] 경로 실수로 인한 404 에러 수정
  index.html
  src/index.css
Labels: bug

#106 [FEAT] study plan calendar
  src/mypage/components/Calendar.tsx
  src/mypage/components/MypageContent.tsx
  src/mypage/components/StudyPlanFetcher.tsx
  src/mypage/css/calendar.css
Labels: enhancement

#105 [FEAT] mypage challenge
  src/mypage/components/Challenge.tsx
Labels: enhancement

#107 Feat/104 withdrawal
  src/App.tsx
  src/mypage/components/MypageContent.tsx
  src/mypage/components/NicknameSection.tsx
Labels: enhancement

#123 [REFACTOR] AI API access_token 인증 추가
  src/ai/api/cookies.ts
  src/ai/api/http.ts
Labels: enhancement

#130 [BUG] AI Sidebar access token 재발급 오류
  src/ai/api/http.ts
  src/ai/components/AiMain.tsx
  src/ai/components/aimain/InputBar.tsx
  src/ai/hook/useInputGate.ts
  src/ai/utils/char.ts
Labels: bug

#137 [FEAT] 8월 26일 03:11 까지 작업한 내용 확인 후, main branch에 병합
  src/community/api/community.ts
  src/community/api/types.ts
  src/community/components/Postcard.tsx
  src/community/hook/useCategoryListCursor.ts
  src/community/post/PostDetail.tsx
  src/community/post/components/CommentList.tsx
  src/community/post/components/CommentsBlock.tsx
  src/community/post/components/LikeButton.tsx
Labels: enhancement

#139 [FEAT] 8월 26일 21:40 까지 작업한 내용 확인 후, main branch에 병합
  README.md
  src/App.tsx
  src/AppContent.tsx
  src/ProtectedRoute.tsx
  src/ai/components/AiSideBar.tsx
  src/ai/components/aimain/InputBar.tsx
  src/community/api/attachments.ts
  src/community/api/community.ts
  src/community/api/presignedJson.ts
  src/community/api/types.ts
  src/community/category/CommunityAll.tsx
  src/community/category/CommunityFree.tsx
  src/community/category/CommunityShare.tsx
  src/community/category/CommunityStudy.tsx
  src/community/components/Postcard.tsx
  src/community/form/CreatePost.tsx
  src/community/form/EditPost.tsx
  src/community/form/PostForm.tsx
  src/community/hook/useComments.ts
  src/community/hook/usePostLike.ts
  src/community/post/PostDetail.tsx
  src/community/post/components/CommentsBlock.tsx
  src/community/post/components/LikeButton.tsx
  src/community/utils/date.ts
  src/landing/components/HeroLanding.tsx
  src/landing/data/featureMosaic.data.ts
  src/mypage/Mypage.tsx
  src/mypage/components/LikedPostsSection.tsx
  src/mypage/components/MyApplications.tsx
  src/mypage/components/MyPostCard.tsx
  src/mypage/components/MyPostsSection.tsx
  src/mypage/components/StudyApplicants.tsx
  src/store/authStore.ts
  src/store/useAuthStore.ts
Labels: enhancement
